### ISSUE TITLE
Intégrer react-i18next pour internationalization.

### ISSUE THREAD

**Issue by QuentinCln** [curb-app/curb-app.github.io#6]
- Ajouter les dépendences de react-i18next au projet
- Créer la configuration pour react-i18next

-  Ajouter un exemple de traduction

sources : 
- https://react.i18next.com/
- http://i18njs.com/

**Comment by QuentinCln** [comment]
packages : 
language detector : 
 - ​browser​
- react native 

bundler : 
- ​i18next-loader​ : webpack loader that can translate your code and generate bundle per each language
-

**Comment by yungkittty** [comment]
"src/services/" => init; HOC / scenes => dymanic load; HOC / components => injection; + provider App;

**Comment by QuentinCln** [comment]
Actual : 

Provider  => App.js

"src/services/ :
- Default namespace => *.json
- init

HOC / scenes : 
-  reprend le HOC de i18n puis load le namespace scoper

pas de HOC / components => utiliser celui de base (i18n HOC) ?

**Comment by QuentinCln** [comment]
Résumé : 
(nommage / emplacement des fichiers à revoir)

Création d'un HOC pour les scenes (HOC par scenes) où il y'a besoin de traduction :

pour connecter une "Scene" à un hoc 

internationalizationHoc({$sceneName}, {$sceneComponent});

$sceneName : 
- la scene est à la racine du dossier scenes/ => "sceneName"
- la scene est une sous scene => "racineScene/subScene/subScene"


Utiliser la traduction dans un Component de la scenes : 

import { translate } from "react-i18next";

t("sceneName":key) => traduction selon le language 

translate(props => props.namespace)(Component);

Format du dossier pour les traductions :

service/internationalization/ :

- index.js : export *.json
- translation/ {sceneName}-{language}.json  (home-en.json)

Changer le language et avoir la langue actuelle :

import {
  changeLanguage,
  getActualLanguage
} from "{{path}}/services/internationalization/i18n";

changeLanguage('en');
getActualLanguage();

**Comment by yungkittty** [comment]
./configs (A confirmer)
  \> ...
  \> ...

./services (A confirmer)
  \> ...

// Michael Jackson style.
./components/i18n-provider-hoc/
  \> index.js
  \> i18n-provider-hoc => I18nProviderHoc (A confirmer, + withI18n())
